"""empty message

Revision ID: 42bbfa09bda6
Revises: 
Create Date: 2018-08-22 22:52:04.866606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42bbfa09bda6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index('dsp_index', table_name='dsp_raw')
    op.drop_table('dsp_raw')
    op.drop_index('dcm_index', table_name='dcm_raw')
    op.drop_table('dcm_raw')
    op.drop_index('report_index', table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('sub_brand', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('ad_campaign_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ad_campaign', mysql.VARCHAR(length=75), nullable=False),
    sa.Column('dsp', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('dsp_campaign_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('dsp_campaign', mysql.VARCHAR(length=75), nullable=False),
    sa.Column('ad_impressions', mysql.FLOAT(), nullable=False),
    sa.Column('ad_clicks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ad_reach', mysql.FLOAT(), nullable=False),
    sa.Column('dsp_impressions', mysql.FLOAT(), nullable=False),
    sa.Column('dsp_clicks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('dsp_cost', mysql.FLOAT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('report_index', 'report', ['date', 'brand', 'sub_brand', 'ad_campaign_id', 'ad_campaign', 'dsp', 'dsp_campaign_id', 'dsp_campaign'], unique=True)
    op.create_table('dcm_raw',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('campaign_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('campaign', mysql.VARCHAR(length=75), nullable=False),
    sa.Column('placement_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('placement', mysql.VARCHAR(length=75), nullable=False),
    sa.Column('impressions', mysql.FLOAT(), nullable=False),
    sa.Column('clicks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reach', mysql.FLOAT(), nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('sub_brand', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('dsp', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('ad_type', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('dcm_index', 'dcm_raw', ['date', 'brand', 'sub_brand', 'campaign_id', 'campaign', 'placement_id', 'placement', 'dsp', 'ad_type'], unique=True)
    op.create_table('dsp_raw',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('campaign_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('campaign', mysql.VARCHAR(length=75), nullable=False),
    sa.Column('impressions', mysql.FLOAT(), nullable=False),
    sa.Column('clicks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cost', mysql.FLOAT(), nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('sub_brand', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('dsp', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('ad_type', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('dsp_index', 'dsp_raw', ['date', 'brand', 'sub_brand', 'campaign_id', 'campaign', 'dsp', 'ad_type'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
